language: node_js
node_js:
  - node
script:
  - npm install -g wrench
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp build
after_script:
  - node_modules/.bin/karma start karma.conf.js
  - COVERALLS_SERVICE_NAME=travis-pro cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf coverage
